### ISSUE TITLE
Addon reports that it isn't available in my country

### ISSUE THREAD

**Issue by gojko81** [AlleSchonWeg/plugin.video.dazn#5]
I'm coming from Germany, since a few days the addon does not function anymore for me. Using it on a Wetek Play2 with Coreelec BS.

**Comment by gojko81** [comment]
Was a problem with DSN

**Comment by AlleSchonWeg** [comment]
Ok. I had this message two weeks ago. The problem was my lan connnection, so my rpi waas not able to initiate a internet connection.

**Comment by gojko81** [comment]
I solved it, it was a dns-setting in my router,

 

Von: AlleSchonWeg [mailto:notifications@github.com] 
Gesendet: Montag, 13. April 2020 20:15
An: AlleSchonWeg/plugin.video.dazn
Cc: gojko81; State change
Betreff: Re: [AlleSchonWeg/plugin.video.dazn] Addon reports that it isn't available in my country (#5)

 

Ok. I had this message two weeks ago. The problem was my lan connnection, so my rpi waas not able to initiate a internet connection.
